/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "SinkModel.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PfylTaskCreated, PfylTaskCreated, AUTO)


PB_BIND(PfylTaskDeleted, PfylTaskDeleted, AUTO)


PB_BIND(PfylTaskState, PfylTaskState, AUTO)




